name: Deploy Desktop

on:
  push:

defaults:
  run:
    working-directory: packages/desktop

jobs:
  update:
    runs-on: ubuntu-20.04
    timeout-minutes: 2
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - name: Set tag as env
        run: yarn prebuild
